version: '3'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb_data:/var/lib/influxdb
    env_file:
      - .env

  mosquitto:
    image: eclipse-mosquitto:1.6
    ports:
      - 1883:1883

#  mosquitto:
#    image: eclipse-mosquitto:latest
#    ports:
#      - "127.0.0.1:1883:1883"
